Allow capturing response for network operations
KDAB/GammaRay pull request #656
Opened 2021-10-31 19:57 UTC by shaan7

The Network Operations tab now contains a checkbox that allows the user
to enable collection of the response body for network replies.

To begin with, we only only collect up to 5MiB of data. In the future we
might make this configurable, and maybe even allow the user to whitelist
to specific Content-Type values.

2021-11-29 19:00 UTC, Waqar144 requested changes

2021-11-29 19:18 UTC, shaan7 commented on plugins/network/networkreplywidget.cpp
> +    connect(ui->responseTextEdit, &QTextEdit::textChanged, this, [this]() {
Good point, I have now changed it to QPlainTextEdit, we can switch to QTextEdit when we implement highlighting or something of that sort.

2021-12-23 18:20 UTC, shaan7 commented on plugins/network/networkreplywidget.cpp
> +            // TODO: Add support for pretty-printing JSON, XML etc
Yeah but I'd rather do this properly in a separate patch by also storing the Content-Type header. Then we can attempt the parse only for `application/json`

2021-12-23 18:22 UTC, shaan7 commented on plugins/network/networkreplywidget.cpp
> +            ui->responseTextEdit->setPlainText(text);
Good idea, done.

2021-12-23 18:26 UTC, shaan7 commented
Recent commits introduce peeking the response also from the downloadProgress signal and some signal connection hackery to ensure we get a chance to read it.
Note that the Network Operations tab has an existing bug where the first few network operations go by undetected (especially if they are too quick), this ends up affecting the response functionality as well.

2021-12-24 06:10 UTC, Waqar144 approved these changes

2021-12-24 13:29 UTC, merged