Fix invokeMethod issues with Qt 6.5
KDAB/GammaRay pull request #778
Opened 2023-04-17 21:53 UTC by vimpostor

Since https://codereview.qt-project.org/c/qt/qtbase/+/422745 there is a new variadic version of QMetaObject::invokeMethod().

However this new variadic version is not compatible with our usage in `Endpoint::invokeObjectLocal()`, as we just dump all 10 parameters at once without caring about the actual function arity.
Theoretically this could be fixed by manually adding 10 if-branches for the correct arity.

However the second much bigger issue is that we don't know the type at compile time, and thus would end up hardcoding all parameter types to `MethodArgument`.

Hence to fix this, we revert back to the non-variadic version by explicitly calling `QMetaObject::invokeMethod()` with `QGenericArgument` as parameters.

Please see the commit message for more details.

Fixes #777

2023-04-19 21:01 UTC, Waqar144 requested changes

2023-04-19 21:02 UTC, Waqar144 commented
The only better fix I can think of is to use the private `invokeMethodImpl` and pass in our arguments.

2023-04-19 21:36 UTC, vimpostor commented on common/endpoint.cpp
> +    QVector<QGenericArgument> g(10);
OK, I have converted them to C-style arrays. Note that we need each `MethodArgument` for the duration of the entire scope and can't just do something like `a[i] = QGenericArgument(MethodArgument(args.at(i)));`, so we do need two arrays.

2023-04-19 21:38 UTC, vimpostor commented
> The only better fix I can think of is to use the private `invokeMethodImpl` and pass in our arguments.

Not sure if it's really better to use private API here. With this current patch we have at least the guarantee that it will continue working until at least Qt 7.0. If it changes then, we probably have to revisit this anyway.

2023-04-19 21:41 UTC, Waqar144 commented on common/endpoint.cpp
> +    QVector<QGenericArgument> g(10);
Thanks

2023-04-19 21:42 UTC, Waqar144 commented
> > The only better fix I can think of is to use the private `invokeMethodImpl` and pass in our arguments.
> 
> Not sure if it's really better to use private API here. With this current patch we have at least the guarantee that it will continue working until at least Qt 7.0. If it changes then, we probably have to revisit this anyway.

For now yes, as the public API essentially does that for us internally

2023-04-19 21:42 UTC, merged

2023-04-20 07:18 UTC, vimpostor commented
Another thing to keep in mind (although this is unrelated to the change in this PR) is that for some strange reason with Qt 6.5 the signal `QuickInspectorClient::features()` fails to fire with the following error message during runtime:

```
QMetaObject::invokeMethod: No such method GammaRay::QuickInspectorClient::features(QFlags<GammaRay::QuickInspectorInterface::Feature>)
Candidates are:
    features(GammaRay::QuickInspectorInterface::Features)
QMetaObject::invokeMethod: No such method GammaRay::QuickInspectorClient::features(QFlags<GammaRay::QuickInspectorInterface::Feature>)
Candidates are:
    features(GammaRay::QuickInspectorInterface::Features)
```

Not sure if this is a bug in Qt, because `GammaRay::QuickInspectorInterface::features` is a literal typedef for `QFlags<GammaRay::QuickInspectorInterface::Feature>` so it should work.

As a workaround the following diff fixes the problem in GammaRay:

```diff
diff --git a/plugins/quickinspector/quickinspectorinterface.h b/plugins/quickinspector/quickinspectorinterface.h
index a1d19474b..c98af8438 100644
--- a/plugins/quickinspector/quickinspectorinterface.h
+++ b/plugins/quickinspector/quickinspectorinterface.h
@@ -86,7 +86,7 @@ public slots:
     virtual void setSlowMode(bool slow) = 0;
 
 signals:
-    void features(GammaRay::QuickInspectorInterface::Features features);
+    void features(QFlags<GammaRay::QuickInspectorInterface::Feature> features);
     void serverSideDecorationChanged(bool enabled);
     void overlaySettings(const GammaRay::QuickDecorationsSettings &settings);
     void slowModeChanged(bool slow);
```

But perhaps this is better fixed in Qt.

2023-04-20 20:00 UTC, Waqar144 commented
> But perhaps this is better fixed in Qt.

I think this is https://codereview.qt-project.org/c/qt/qtbase/+/399035

I have already put some work arounds for our property view to make this work.

Perhaps we can register the alias metatype and it will work?

2023-04-20 20:34 UTC, vimpostor commented
> Perhaps we can register the alias metatype and it will work?

There already is a `Q_DECLARE_METATYPE(GammaRay::QuickInspectorInterface::Features)` and a `StreamOperators::registerOperators<Features>();`.
When I try to additionally register `Q_DECLARE_METATYPE(QFlags<GammaRay::QuickInspectorInterface::Feature>)`, I get an duplicate metatype id error and if I replace it instead of adding, then it still doesn't work.

It also doesn't work if I `qRegister<QFlags<GammaRay::QuickInspectorInterface::Feature>>()` .

Any other ideas?

2023-04-20 21:06 UTC, Waqar144 commented
To register an alias, I think it should be `qRegisterMetaType<QFlags<GammaRay::QuickInspectorInterface::Feature>>("alias")`

2023-04-20 21:15 UTC, vimpostor commented
> To register an alias, I think it should be `qRegisterMetaType<QFlags<GammaRay::QuickInspectorInterface::Feature>>("alias")`

That unfortunately doesn't work either. :(

2023-04-26 19:59 UTC, vimpostor commented
It looks like this problem is not just with `QFlags`, but with all kinds of typedefs and `using` declarations, e.g. `using ObjectIds = QVector<class ObjectId>;` is affected as well, which causes the Quick scene object picker to not work anymore:

```
QMetaObject::invokeMethod: No such method GammaRay::RemoteViewClient::elementsAtReceived(QList<GammaRay::ObjectId>,int)
Candidates are:
    elementsAtReceived(GammaRay::ObjectIds,int)

// ^ above type mismatch is literally the `using` declaration from above
```

Perhaps we can send some more type info, so that we can construct the type for `invokeMethod` more correctly at the receiver side, but I am not sure if it's possible.

2023-04-28 07:32 UTC, Waqar144 commented
A simpler and likely more robust solution for the  above is to just use the real type. Aliases are just sugar anyways.